# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: airport
      POSTGRES_USER: flight
      POSTGRES_DB: algo

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"